# get api_id & api_hash from my.telegram.org
api_id: '22658021'
api_hash: '6da533e7c45bc668182b5a0f5a4497dd'
# 13 digit channel id startswith - like -111.......
dump_id: '-1002493542474'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: 'BQFZu-UApeis2HBl13VY9nej7OsxKmm3IOGn5g8rR67Hw5Vc6SOYS26hQ950Yt2ykT0Hr8poI17R87avVd2OQTwdkgamZhmsMIcmnWBN9eGvK2Ajuc39lBjWYnGsNrc7_JGK3Kh3e_m61_r-_lVBFuGnbA4L6TTz4drCHK-g4AjHcCy1MqdKyL0SiE1bPb_WfWrlLdYSCTUzcFZ4JU9Tg0fv548GL5h0l_s9kFk3MQFMZ2jzdCjkPGY4b-zehJg4X3SglSFZ8IIbZDDFS5do83CpVhJK77DtfAPvGSV4FZYDG2iFOupdlkSSglMmVr54w3lnoj8s_wngYwMs2guCDp7LoZiFPAAAAAGvYMA0AA'
